config/routes.rb
Rails.application.routes.draw do
  root 'tutorial_maps#index'

  # Aether Eggs Pages
  scope 'eggs' do
    # TUTORIAL PAGES
    get 'tutorial', to: 'tutorial_maps#index', as: 'tutorial'
    get 'tutorial/:mapname', to: 'tutorial_maps#map', as: 'tutorial_map'
    get 'tutorial/:mapname/:type/:id', to: 'tutorial_maps#steps', as: 'tutorial_steps'
    get 'tutorial/:mapname/:type/:id/edit', to: 'tutorial_maps#edit', as: 'tutorial_edit'

    # Bot Pages
    #
    get 'bot', to: 'bot#index', as: 'bot'
  end

  scope 'cup' do
  end
end

app/models/Map.rb
class Map
  attr_accessor :id, :name, :ee, :ww, :uww, :extras

  def initialize(id, name, ee, ww, uww, extras)
    @id = id
    @name = name
    @ee = ee
    @ww = ww
    @uww = uww
    @extras = extras
  end
end

app/models/Subitem.rb
class Subitem
  attr_accessor :id, :mapname, :name, :steps

  def initialize(id, mapname, name, steps)
    @id = id
    @mapname = mapname
    @name = name
    @steps = steps
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bot_controller.rb
class BotController < ApplicationController
  def index
  end
end

app/controllers/tutorial_maps_controller.rb
class TutorialMapsController < ApplicationController
  before_action except: :public
  caches_action :index, layout: true, expires_in: 3.hours
  caches_action :map, layout: true, expires_in: 3.hours
  caches_action :edit, layout: true, expires_in: 3.hours
  caches_action :steps, layout: true, expires_in: 3.hours

  API_URL = ENV['API_URL']

  def index
    url = '/allmaps/names'

    result_json = get_request(url)

    @mapnames = result_json
  end

  def map
    mapname = params[:mapname]
    url = "/tutoriais/#{mapname}"
    result_json = get_request(url)
    return unless result_json

    @map = Map.new(
      '',
      result_json['name'],
      parse_item(result_json['ee']),
      parse_item(result_json['ww']),
      parse_item(result_json['uww']),
      parse_item(result_json['extras'])
    )
  end

  def edit
    mapname = params[:mapname]
    tipo = params[:type]
    id = params[:id]

    is_dig = /\A[-+]?\d+\z/ === id

    render 'notfound' unless is_dig

    url = "/tutoriais/#{mapname}/#{tipo}"

    result_json = get_request(url)
    return unless result_json

    @subitems = parse_item(result_json)[id.to_i]
  end

  def steps
    mapname = params[:mapname]
    tipo = params[:type]
    id = params[:id]

    is_dig = /\A[-+]?\d+\z/ === id

    render 'notfound' unless is_dig

    url = "/tutoriais/#{mapname}/#{tipo}"

    result_json = get_request(url)
    return unless result_json

    @subitems = parse_item(result_json)[id.to_i]
  end

  private

  def get_request(url)
    response = HTTParty.get(API_URL + url)

    JSON.parse(response.body)
  rescue Errno::ECONNREFUSED
    render 'apiError'
    false
  rescue URI::InvalidURIError
    render 'notfound'
    false
  end

  def parse_item(result_json)
    i = -1
    result_json.map do |e|
      Subitem.new(
        i += 1,
        e['mapName'],
        e['name'],
        e['steps']
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bot_helper.rb
module BotHelper
end

app/helpers/tutorial_maps_helper.rb
module TutorialMapsHelper
  def clear_img_url(url)
    url.gsub('$file:', '')
  end
end

app/views/bot/index.html.erb
<h1>main</h1>

<button type="button">Adicionar no seu servidor</button>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li> <%= link_to 'Maps', tutorial_path %> </li>
    <li> <%= link_to 'Bot', bot_path %> </li>
    <li> <%= link_to 'API', '#' %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aethereggs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- BOOTSTRAP CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- BOOTSTRAP JAVASCRIPT -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tutorial_maps/_editTutorialStep.html.erb
<ul>
  <% steps.steps.each do |step| %>
    <li class="tutorial-step">
      <% if step.start_with?("$file") %>
        <div class="tutorial-center-image">
          <img src="<%= clear_img_url step %>" alt="">
        </div>
      <% else %>
        <p>
        <div contenteditable>
          <%= step %>
        </div>
        </p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tutorial_maps/_tutorialstep.html.erb
<ul>
  <% steps.steps.each do |step| %>
    <li class="tutorial-step">
      <% if step.start_with?("$file") %>
        <div class="tutorial-center-image">
          <img src="<%= clear_img_url step %>" alt="">
        </div>
      <% else %>
        <%= step %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tutorial_maps/apiError.html.erb
<h1>Alguns de nossos serviços estão offline, tente novamente mais tarde</h1>

app/views/tutorial_maps/edit.html.erb
<h1 class="text-center">Bem vindo ao modo de edição</h1>
<p>Aqui você pode editar os textos que quiser. Quando terminar, seu tutorial será levado á análise, para que possa ser verificada e aprovada!</p>
<h3><%= @subitems.name %></h3>
<%= render "editTutorialStep", steps: @subitems %>

app/views/tutorial_maps/index.html.erb
<% @mapnames.each do |item| %>
  <h4><%= link_to item, tutorial_map_path(item)%></h4>
<% end %>

app/views/tutorial_maps/map.html.erb
<h1><%= @map.name %></h1>

<h1>Easter Egg</h1>
<% @map.ee.each do |item| %>
  <h4><%= link_to item.name, tutorial_steps_path(@map.name, "ee", item.id)%></h4>
<% end %>
<h1>Wonder Weapon</h1>
<% @map.ww.each do |item| %>
  <h4><%= link_to item.name, tutorial_steps_path(@map.name, "ww", item.id)%></h4>
<% end %>
<h1>Upgrade Wonder Weapon</h1>
<% @map.uww.each do |item| %>
  <h4><%= link_to item.name, tutorial_steps_path(@map.name, "uww", item.id)%></h4>
<% end %>
<h1>Extras</h1>
<% @map.extras.each do |item| %>
  <h4><%= link_to item.name, tutorial_steps_path(@map.name, "extras", item.id)%></h4>
<% end %>

app/views/tutorial_maps/notfound.html.erb
<h1>Não foi possíbel localizar o tutorial</h1>

app/views/tutorial_maps/steps.html.erb
<h1><%= @subitems.name %></h1>
<%= render "tutorialstep", steps: @subitems %>
<div class="tutorial-footer">
  <ul>
    <li> <%= link_to "Edit this Tutorial", "#{@subitems.id}/edit"%> </li>
  </ul>
</div>